name: "@potatoes/lib-ui: PR to main"

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/lib-ui/**'

jobs:
  tests:
    if: ${{github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/test.yaml@main
    with:
      node_registry_url: 'https://npm.pkg.github.com'
      node_scope: '@potatoes'
      node_cache: 'npm'
      install_command: 'npm ci -w packages/lib-ui'
      test_command: 'npm run test -w packages/lib-ui'
